version: "3.7"

services:
  postgres: # container
    container_name: postgres_container
    image: postgres # image from docker hub
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432" # map container's 5432 port to host's 5432 port
    networks: # Specify custom network
      - postgres
    restart: unless-stopped

  pgadmin: # container
    container_name: pgadmin_container
    image: dpage/pgadmin4 # image from docker hub
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80" # map container's 80 port to host's 5050 port
    networks: # Specify custom network
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
